#https://raw.githubusercontent.com/Orain/ansible-playbook/master/.travis.yml
language: php
php:
  - 5.4

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
script:
  # Check php script syntax
  - bash .travis.phplint.sh

notifications:
  email:
    recipients:
      - southparkfan223@hotmail.com
    on_success: change
    on_failure: always
